# Book settings
title: "Data Science Curriculum"
author: "James Irving, PhD"
logo: assets/images/flatironschool_banner.jpg

# Force re-execution of notebooks on each build? See docs
execute:
  execute_notebooks: "off"

# Exclude files not referenced in _toc.yml to avoid corrupt/stray notebooks
exclude_patterns:
  - "**/_build/**"
  - "**/instructor/**"
  - "**/student/**"
  - "**/old/**"
  - "**/scratch_notebooks/**"
  - "**/WIP/**"
  - "Phase_4/topic_36_recommendation_systems/dsc-implementing-recommender-systems-lab/solution.ipynb"
  - "Phase_4/topic_36_recommendation_systems/CL Repo/**"
  - "Phase_3/topic_29_decision_trees/instructor/**"
  - "Phase_3/topic_22_linear_algebra/instructor/**"
  - "Phase_3/topic_30_ensemble_methods/instructor/**"

# Information about where the book exists on the web
repository:
  url: https://github.com/jirvingphd/Online-DS-FT-022221-Cohort-Notes-FLEX
  path_to_book: ""
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Launch buttons
launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: false
